name: Build EvtScan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Container
        run: docker build -t nhibiki/evtscan:latest .
      - name: Login Docker Registry
        run: docker login --username ${{ secrets.DUSER }} --password ${{ secrets.DPASS }}
      - name: Push Container
        run: docker push nhibiki/evtscan:latest
      - name: Clean Up
        run: docker logout
